export interface TTSRequest { text:string; voice?:string; format?:'mp3'|'wav'; }
export interface TTSResult { audio:Uint8Array; contentType:string; }
export interface TTSProvider { name:string; synthesize(req:TTSRequest):Promise<TTSResult>; }
export class OpenAITTS implements TTSProvider{ name='openai'; constructor(private key:string,private model='gpt-4o-mini-tts',private defaultVoice='alloy'){} async synthesize(r:TTSRequest){const res=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{'authorization':`Bearer ${this.key}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,voice:r.voice??this.defaultVoice,input:r.text,response_format:r.format??'mp3'})});if(!res.ok)throw new Error(await res.text());return{audio:new Uint8Array(await res.arrayBuffer()),contentType:(r.format??'mp3')==='wav'?'audio/wav':'audio/mpeg'}}}
export class ElevenLabsTTS implements TTSProvider{ name='elevenlabs'; constructor(private key:string,private voiceId:string){} async synthesize(r:TTSRequest){const res=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(r.voice??this.voiceId)}`,{method:'POST',headers:{'xi-api-key':this.key,'content-type':'application/json','accept':'audio/mpeg'},body:JSON.stringify({text:r.text,model_id:'eleven_multilingual_v2'})});if(!res.ok)throw new Error(await res.text());return{audio:new Uint8Array(await res.arrayBuffer()),contentType:'audio/mpeg'}}}
export class GoogleTTS implements TTSProvider{ name='google'; constructor(private key:string,private language='en-US',private voice='en-US-Neural2-F'){} async synthesize(r:TTSRequest){const res=await fetch(`https://texttospeech.googleapis.com/v1/text:synthesize?key=${encodeURIComponent(this.key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:{text:r.text},voice:{languageCode:this.language,name:r.voice??this.voice},audioConfig:{audioEncoding:'MP3'}})});if(!res.ok)throw new Error(await res.text());const j:any=await res.json();return{audio:Uint8Array.from(atob(j.audioContent), c => c.charCodeAt(0)),contentType:'audio/mpeg'}}}
export function estimateDurationMs(text:string,wpm=165){return Math.max(1200,Math.round(text.trim().split(/\s+/).length/wpm*60_000))}

export class AzureSpeechTTS implements TTSProvider{ name='azure'; constructor(private key:string,private region:string,private defaultVoice='en-US-AvaMultilingualNeural'){} async synthesize(r:TTSRequest){const ssml=`<speak version="1.0" xml:lang="en-US"><voice name="${r.voice??this.defaultVoice}">${r.text.replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]!))}</voice></speak>`;const res=await fetch(`https://${this.region}.tts.speech.microsoft.com/cognitiveservices/v1`,{method:'POST',headers:{'Ocp-Apim-Subscription-Key':this.key,'Content-Type':'application/ssml+xml','X-Microsoft-OutputFormat':'audio-24khz-48kbitrate-mono-mp3'},body:ssml});if(!res.ok)throw new Error(await res.text());return{audio:new Uint8Array(await res.arrayBuffer()),contentType:'audio/mpeg'}}}
export function createTTSProvider(env:Record<string,string|undefined>):TTSProvider|null{const p=(env.TTS_PROVIDER??'browser').toLowerCase();if(p==='openai'&&env.OPENAI_API_KEY)return new OpenAITTS(env.OPENAI_API_KEY);if(p==='elevenlabs'&&env.ELEVENLABS_API_KEY&&env.TTS_VOICE)return new ElevenLabsTTS(env.ELEVENLABS_API_KEY,env.TTS_VOICE);if(p==='azure'&&env.AZURE_SPEECH_KEY&&env.AZURE_SPEECH_REGION)return new AzureSpeechTTS(env.AZURE_SPEECH_KEY,env.AZURE_SPEECH_REGION,env.TTS_VOICE);if(p==='google'&&env.GOOGLE_TTS_API_KEY)return new GoogleTTS(env.GOOGLE_TTS_API_KEY);return null}
