import { promises as fs } from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { createEmptyIAM, type Component, type Evidence, type IAM } from '@interactive-archify/core';
export interface AnalyzeProgress { stage:string; current:number; total?:number; detail?:string; }
export interface AnalyzeOptions { maxFiles?:number; maxFileBytes?:number; onProgress?:(p:AnalyzeProgress)=>void; }
const IGNORE=new Set(['.git','node_modules','.next','dist','build','coverage','.venv','venv','target','vendor']);
const SECRET_FILE=/(^|\/)(\.env($|\.)|id_rsa|id_ed25519|credentials|secrets?\.(json|ya?ml))/i;
const BINARY=/\.(png|jpe?g|gif|webp|ico|pdf|zip|gz|tar|7z|mp[34]|mov|wav|woff2?|ttf|eot|exe|dll|so|dylib)$/i;
function redact(s:string){return s.replace(/((api[_-]?key|secret|token|password|authorization)\s*[:=]\s*["']?)([^\s"']+)/ig,'$1[REDACTED]').replace(/sk-[A-Za-z0-9_-]{16,}/g,'[REDACTED_OPENAI_KEY]');}
async function walk(root:string,opts:AnalyzeOptions){const out:string[]=[]; async function rec(dir:string){if(out.length>=(opts.maxFiles??5000))return; for(const d of await fs.readdir(dir,{withFileTypes:true})){if(IGNORE.has(d.name))continue; const full=path.join(dir,d.name); if(d.isDirectory())await rec(full); else if(!BINARY.test(d.name)&&!SECRET_FILE.test(full)) out.push(full); if(out.length>=(opts.maxFiles??5000))return;}} await rec(root); return out;}
const detectors:Array<{id:string;re:RegExp;name:string;type:Component['type'];layer:string}>=[
{id:'nextjs',re:/"next"\s*:/i,name:'Next.js Web',type:'frontend',layer:'experience'},{id:'react',re:/"react"\s*:/i,name:'React Frontend',type:'frontend',layer:'experience'},
{id:'express',re:/\bexpress\b/i,name:'Express API',type:'api',layer:'application'},{id:'fastapi',re:/\bFastAPI\b/i,name:'FastAPI',type:'api',layer:'application'},{id:'nestjs',re:/@nestjs\//i,name:'NestJS API',type:'api',layer:'application'},
{id:'postgres',re:/postgres(ql)?|pg:\/\//i,name:'PostgreSQL',type:'database',layer:'data'},{id:'mysql',re:/mysql/i,name:'MySQL',type:'database',layer:'data'},{id:'mongo',re:/mongodb|mongoose/i,name:'MongoDB',type:'database',layer:'data'},
{id:'redis',re:/\bredis\b/i,name:'Redis',type:'cache',layer:'data'},{id:'kafka',re:/\bkafka\b/i,name:'Kafka',type:'event-bus',layer:'messaging'},{id:'rabbitmq',re:/rabbitmq|amqp/i,name:'RabbitMQ',type:'queue',layer:'messaging'},
{id:'stripe',re:/\bstripe\b/i,name:'Stripe',type:'external-service',layer:'context'},{id:'openai',re:/openai/i,name:'OpenAI API',type:'external-service',layer:'context'},{id:'aws',re:/aws_|amazonaws|@aws-sdk/i,name:'AWS',type:'cloud-service',layer:'infrastructure'},
{id:'prom',re:/prometheus/i,name:'Prometheus',type:'monitoring',layer:'observability'},{id:'grafana',re:/grafana/i,name:'Grafana',type:'monitoring',layer:'observability'}];
export async function analyzeRepository(root:string,opts:AnalyzeOptions={}):Promise<IAM>{const abs=path.resolve(root); const st=await fs.stat(abs); if(!st.isDirectory())throw new Error('Repository path must be a directory'); opts.onProgress?.({stage:'Scanning repository',current:0}); const files=await walk(abs,opts); const iam=createEmptyIAM(path.basename(abs)); const found=new Map<string,Component>(); const evidence:Evidence[]=[]; let i=0;
for(const file of files){i++; opts.onProgress?.({stage:'Analyzing files',current:i,total:files.length,detail:path.relative(abs,file)}); let stat; try{stat=await fs.stat(file)}catch{continue} if(stat.size>(opts.maxFileBytes??512_000))continue; let content=''; try{content=redact(await fs.readFile(file,'utf8'))}catch{continue} const rel=path.relative(abs,file).replaceAll(path.sep,'/');
for(const d of detectors) if(d.re.test(content)||d.re.test(rel)){const eid=`evidence-${d.id}-${crypto.createHash('sha1').update(rel).digest('hex').slice(0,8)}`; evidence.push({id:eid,type:/docker|k8s|terraform|helm/i.test(rel)?'infrastructure':/package|requirements|pyproject|pom|gradle/i.test(rel)?'manifest':'source',file:rel,confidence:'verified'}); const existing=found.get(d.id); if(existing){existing.evidenceIds=[...(existing.evidenceIds??[]),eid]} else found.set(d.id,{id:d.id,name:d.name,type:d.type,layer:d.layer,technology:d.name,description:`Detected from repository evidence.`,confidence:'verified',evidenceIds:[eid]});}
// route/API evidence
if(/(app\.(get|post|put|delete)|router\.(get|post|put|delete)|@app\.(get|post|put|delete)|export\s+async\s+function\s+(GET|POST|PUT|DELETE))/i.test(content)){const id='application-api'; const eid=`evidence-api-${crypto.createHash('sha1').update(rel).digest('hex').slice(0,8)}`; evidence.push({id:eid,type:'source',file:rel,confidence:'verified'}); if(!found.has(id))found.set(id,{id,name:'Application API',type:'api',layer:'application',confidence:'verified',description:'HTTP/API handlers were detected.',evidenceIds:[eid]}); else found.get(id)!.evidenceIds!.push(eid);}
}
iam.evidence=evidence; iam.components=[{id:'user',name:'User',type:'user',layer:'context',confidence:'inferred',description:'External user/client context.'},...found.values()]; const front=iam.components.find(c=>c.type==='frontend'); const api=iam.components.find(c=>c.type==='api'); if(front&&api)iam.relationships.push({id:`${front.id}-to-${api.id}`,source:front.id,target:api.id,protocol:'HTTPS',confidence:'inferred'}); else if(api)iam.relationships.push({id:`user-to-${api.id}`,source:'user',target:api.id,protocol:'HTTPS',confidence:'inferred'}); if(front)iam.relationships.unshift({id:`user-to-${front.id}`,source:'user',target:front.id,protocol:'HTTPS',confidence:'inferred'});
const services=iam.components.filter(c=>['api','service','frontend'].includes(c.type)); const deps=iam.components.filter(c=>['database','cache','queue','event-bus','external-service','cloud-service','monitoring'].includes(c.type)); const source=api??services.at(-1); if(source)for(const d of deps)iam.relationships.push({id:`${source.id}-to-${d.id}`,source:source.id,target:d.id,protocol:d.type==='database'?'SQL':d.type==='cache'?'Redis':d.type==='queue'||d.type==='event-bus'?'Event':d.type==='monitoring'?'Telemetry':'HTTPS',confidence:'inferred',evidenceIds:d.evidenceIds?.slice(0,1)});
if(iam.relationships.length){const start=front??api??iam.components[0]!; const steps=[start,...deps.slice(0,3)].filter(Boolean).map((c,idx,arr)=>({componentId:c.id,relationshipId:idx?iam.relationships.find(r=>r.source===arr[idx-1]!.id&&r.target===c.id)?.id:undefined})); iam.flows.push({id:'detected-primary-flow',name:'Detected Primary Flow',confidence:'inferred',steps});}
opts.onProgress?.({stage:'Repository analysis complete',current:files.length,total:files.length}); return iam;}
